using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Services.Domain.Composite
{
    ///////////////////////////////////////////////////////////
    //  Component.cs
    //  Implementation of the Class Component
    //  Generated by Enterprise Architect
    //  Created on:      02-may.-2024 21:18:24
    //  Original author: gaston
    ///////////////////////////////////////////////////////////

    /// <summary>
    /// Clase abstracta que representa un acceso. 
    /// Define la estructura básica para componentes que pueden ser agregados o removidos,
    /// así como para obtener el conteo de dichos componentes.
    /// </summary>
    public abstract class Acceso
    {
        /// <summary>
        /// Identificador único del acceso.
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Nombre del acceso.
        /// </summary>
        public string Nombre { get; set; }

        /// <summary>
        /// Constructor por defecto.
        /// </summary>
        public Acceso()
        {
        }

        /// <summary>
        /// Método abstracto para agregar un componente de tipo Acceso.
        /// </summary>
        /// <param name="component">El componente a agregar.</param>
        public abstract void Add(Acceso component);

        /// <summary>
        /// Método abstracto para remover un componente de tipo Acceso.
        /// </summary>
        /// <param name="component">El componente a remover.</param>
        public abstract void Remove(Acceso component);

        /// <summary>
        /// Método abstracto para obtener el conteo de componentes.
        /// </summary>
        /// <returns>El número de componentes.</returns>
        public abstract int GetCount();
    } // end Component
}
