//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Clase que representa el contexto de la base de datos para la gestión del flujo de trabajo.
    /// Hereda de <see cref="DbContext"/> y se utiliza para interactuar con la base de datos.
    /// </summary>
    public partial class GestionWorkFlowEntities : DbContext
    {

        /// <summary>
        /// Constructor de la clase <see cref="GestionWorkFlowEntities"/> que inicializa la conexión a la base de datos
        /// utilizando el nombre de la cadena de conexión configurada en el archivo de configuración.
        /// </summary>
        public GestionWorkFlowEntities()
            : base("name=GestionWorkFlowEntities")
        {
        }

        /// <summary>
        /// Método sobrecargado para configurar el modelo de datos utilizando <see cref="DbModelBuilder"/>.
        /// Este método lanza una excepción para evitar el uso de Code First en lugar de un modelo basado en base de datos.
        /// </summary>
        /// <param name="modelBuilder">El objeto <see cref="DbModelBuilder"/> utilizado para configurar el modelo de datos.</param>
        /// <exception cref="UnintentionalCodeFirstException">Lanzada para evitar la configuración de Code First.</exception>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Representa la colección de <see cref="BONO"/> en la base de datos.
        /// </summary>
        public virtual DbSet<BONO> BONO { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="CLIENTE"/> en la base de datos.
        /// </summary>
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="DETALLE_PEDIDO"/> en la base de datos.
        /// </summary>
        public virtual DbSet<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="DETALLE_TAREA"/> en la base de datos.
        /// </summary>
        public virtual DbSet<DETALLE_TAREA> DETALLE_TAREA { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="EMPLEADO"/> en la base de datos.
        /// </summary>
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="PEDIDO"/> en la base de datos.
        /// </summary>
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="PRODUCTO"/> en la base de datos.
        /// </summary>
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }

        /// <summary>
        /// Representa la colección de <see cref="TAREA"/> en la base de datos.
        /// </summary>
        public virtual DbSet<TAREA> TAREA { get; set; }
    }
}
