//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representa un bono que puede ser asignado a empleados.
    /// </summary>
    public partial class BONO
    {
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="BONO"/>.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BONO()
        {
            this.EMPLEADO = new HashSet<EMPLEADO>();
        }

        /// <summary>
        /// Obtiene o establece el identificador único del bono.
        /// </summary>
        public Guid ID_BONO { get; set; }

        /// <summary>
        /// Obtiene o establece la categoría del bono (por ejemplo, rendimiento, asistencia).
        /// </summary>
        public string CATEGORIA { get; set; }

        /// <summary>
        /// Obtiene o establece el monto del bono.
        /// </summary>
        public decimal MONTO { get; set; }

        /// <summary>
        /// Obtiene o establece el número mínimo de tareas que un empleado debe completar para ser elegible para el bono.
        /// </summary>
        public int MINIMO_TAREAS { get; set; }

        /// <summary>
        /// Obtiene o establece el estado del bono (por ejemplo, activo o inactivo).
        /// </summary>
        public bool ESTADO { get; set; }

        /// <summary>
        /// Obtiene la colección de empleados asociados a este bono.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPLEADO> EMPLEADO { get; set; }
    }
}
