//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representa un cliente en el sistema.
    /// </summary>
    public partial class CLIENTE
    {
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="CLIENTE"/>.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }

        /// <summary>
        /// Obtiene o establece el identificador único del cliente.
        /// </summary>
        public Guid ID_CLIENTE { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del cliente.
        /// </summary>
        public string NOMBRE { get; set; }

        /// <summary>
        /// Obtiene o establece el apellido del cliente.
        /// </summary>
        public string APELLIDO { get; set; }

        /// <summary>
        /// Obtiene o establece el número de documento de identidad (DNI) del cliente.
        /// </summary>
        public int DNI { get; set; }

        /// <summary>
        /// Obtiene o establece el estado del cliente (por ejemplo, activo o inactivo).
        /// </summary>
        public bool ESTADO { get; set; }

        /// <summary>
        /// Obtiene la colección de pedidos asociados a este cliente.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
