//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representa un detalle de un pedido en el sistema, que incluye información sobre los productos solicitados.
    /// </summary>
    public partial class DETALLE_PEDIDO
    {
        /// <summary>
        /// Obtiene o establece el identificador único del detalle del pedido.
        /// </summary>
        public Guid ID_DETALLE { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador del pedido al que pertenece este detalle.
        /// </summary>
        public Guid ID_PEDIDO { get; set; }

        /// <summary>
        /// Obtiene o establece el identificador del producto asociado a este detalle de pedido.
        /// </summary>
        public Guid ID_PRODUCTO { get; set; }

        /// <summary>
        /// Obtiene o establece la cantidad del producto en este detalle de pedido.
        /// </summary>
        public int CANTIDAD { get; set; }

        /// <summary>
        /// Obtiene o establece el pedido asociado a este detalle.
        /// </summary>
        public virtual PEDIDO PEDIDO { get; set; }

        /// <summary>
        /// Obtiene o establece el producto asociado a este detalle de pedido.
        /// </summary>
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
