//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representa un producto en el sistema, incluyendo información sobre su nombre, descripción, precio y estado.
    /// </summary>
    public partial class PRODUCTO
    {
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="PRODUCTO"/>.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_PEDIDO = new HashSet<DETALLE_PEDIDO>();
        }

        /// <summary>
        /// Obtiene o establece el identificador único del producto.
        /// </summary>
        public Guid ID_PRODUCTO { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre del producto.
        /// </summary>
        public string NOMBRE { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción del producto.
        /// </summary>
        public string DESCRIPCION { get; set; }

        /// <summary>
        /// Obtiene o establece el precio del producto.
        /// </summary>
        public decimal PRECIO { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo de producto (por ejemplo, "Electrónico", "Alimento", etc.).
        /// </summary>
        public string TIPO { get; set; }

        /// <summary>
        /// Obtiene o establece el estado del producto (por ejemplo, disponible o no disponible).
        /// </summary>
        public bool ESTADO { get; set; }

        /// <summary>
        /// Obtiene la colección de detalles de pedido asociados a este producto.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
    }
}
