//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Representa una tarea en el sistema, incluyendo información sobre su nombre, descripción y estado.
    /// </summary>
    public partial class TAREA
    {
        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="TAREA"/>.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAREA()
        {
            this.DETALLE_TAREA = new HashSet<DETALLE_TAREA>();
        }

        /// <summary>
        /// Obtiene o establece el identificador único de la tarea.
        /// </summary>
        public Guid ID_TAREA { get; set; }

        /// <summary>
        /// Obtiene o establece el nombre de la tarea.
        /// </summary>
        public string NOMBRE { get; set; }

        /// <summary>
        /// Obtiene o establece la descripción de la tarea.
        /// </summary>
        public string DESCRIPCION { get; set; }

        /// <summary>
        /// Obtiene o establece el estado de la tarea (por ejemplo, "Pendiente", "En Progreso", "Completada").
        /// </summary>
        public string ESTADO { get; set; }

        /// <summary>
        /// Obtiene la colección de detalles de tarea asociados a esta tarea.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_TAREA> DETALLE_TAREA { get; set; }
    }
}
